// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import { github } from 'projen';
import { OrgTenancy } from './';

/**
 * CdkCommonOptions
 */
export interface CdkCommonOptions {
  /**
   * Whether to enable the auto merge workflow for PRs.
   * This will enable the auto merge workflow as well as the merge queue
   * @default - true for private projects, false otherwise
   */
  readonly enablePRAutoMerge?: boolean;
  /**
   * Options for the GitHub auto merge workflow.
   * That is the workflow that turns on auto merge on all PRs.
   * @default - default options
   */
  readonly ghAutoMergeOptions?: github.AutoQueueOptions;
  /**
   * Whether or not this package is private.
   * Setting this variable to true means that your project is created with sane defaults for private repositories.
   * @default true
   */
  readonly private?: boolean;
  /**
   * Set a minimal node version via the engines field
   * Set this to `false` if a package did not enforce this previously and we don't want to change this for now.
   * @default true
   */
  readonly setNodeEngineVersion?: boolean;
  /**
   * The organization this project is part of.
   * @default - Auto detected from package name
   */
  readonly tenancy?: OrgTenancy;
  /**
   * Whether to enable the separate workflow to upgrade the cdklabs-projen-project-types dependencies.
   * @default true
   */
  readonly upgradeCdklabsProjenProjectTypes?: boolean;
  /**
   * Whether to have a separate workflow to upgrade runtime deps and mark this PR as fix.
   * @default true
   */
  readonly upgradeRuntimeDepsAsFix?: boolean;
}
