// ~~ Generated by projen. To modify, edit .projenrc.ts and run "yarn projen".

/**
 * VsCodeWorkspaceOptions
 */
export interface VsCodeWorkspaceOptions {
  /**
   * Adds a workspace for the repository root. This can be useful to manage the repository configuration.
   * @default false
   */
  readonly includeRootWorkspace?: boolean;
  /**
   * The name of the root workspace if included.
   * @default <root>
   */
  readonly rootWorkspaceName?: string;
}
